## <strong> 4. Pandas 객체 생성 및 조작 </strong>

```Pandas``` 라이브러리 설치

In [1]:
!pip install pandas

Requirement already satisfied: pandas in .\anaconda3\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in .\anaconda3\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\anaconda3\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
# 헬프 문서 출력
pd?

Type:        module
String form: <module 'pandas' from 'C:\\Users\\chach\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\chach\anaconda3\lib\site-packages\pandas\__init__.py
Docstring:
pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

In [4]:
# 라이브러리 버전 확인
pd.__version__

'3.0.1'

### Pandas 객체: <strong> Series </strong>

In [6]:
# [+] List 객체에서 Series 객체를 생성
ser = pd.Series([0.25,0.5,0.75,1.0])
ser

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [9]:
# Pandas 객체 속성: .values
vals = ser.values
vals
type(vals)

numpy.ndarray

In [8]:
# Pandas 객체 속성: .index
ind = ser.index
print(ind)
print(list(ind))

RangeIndex(start=0, stop=4, step=1)
[0, 1, 2, 3]

In [12]:
# [+] 레이블 기반 인덱싱
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a','b','c','d'])
print(ser)
print(ser['a'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25

### <strong> Dictionary와 Series 객체 </strong>

In [13]:
# Dictionary 객체에서 Series 객체를 생성
population_dict = {
    'California': 38332521,   # 미국 연방주 별 인구
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [16]:
# [+] 레이블 기반 인덱싱: 'California'에서 'New York'까지
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

### Pandas 객체:<strong> DataFrame </strong>

In [17]:
# 미국 연방주 별 면적
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'New York': 141297,
    'Florida': 170312,
    'Illinois': 149995
}

area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [19]:
# [+] 'population'과 'area' Series 객체를 포함하는 DataFrame 객체 생성
states = pd.DataFrame({'population' : population, 'area' : area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
# DataFrame 객체의 인덱스와 컬럼
print(states.index)
print(states.columns)

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='str')
Index(['population', 'area'], dtype='str')

In [21]:
# [+] DataFrame으로부터 Series 객체 접근하기
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

#### **NumPy 배열로부터 DataFrame 객체 생성**
+ 예제, 오늘의 운세: 금전운(```money_fortune```), 연애운(```love_fortune```)

In [25]:
# [+] 실수 난수로 이루어진 12X2 크기의 NumPy 배열 생성
arr = np.random.rand(12,2)
arr

array([[0.73099515, 0.27201076],
       [0.97035665, 0.51571406],
       [0.07561445, 0.64651283],
       [0.06467504, 0.3754222 ],
       [0.94021071, 0.08109297],
       [0.90775397, 0.63783176],
       [0.36424219, 0.55390577],
       [0.4668588 , 0.84450469],
       [0.70374769, 0.73447245],
       [0.00226296, 0.0727695 ],
       [0.91895562, 0.40910113],
       [0.78063982, 0.0652474 ]])

In [26]:
# NumPy 배열로부터 DataFrame 객체 생성
df = pd.DataFrame(
    arr, 
    columns=['money_fortune', 'love_fortune'], 
    index=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
)

df

     money_fortune  love_fortune
Jan       0.730995      0.272011
Feb       0.970357      0.515714
Mar       0.075614      0.646513
Apr       0.064675      0.375422
May       0.940211      0.081093
Jun       0.907754      0.637832
Jul       0.364242      0.553906
Aug       0.466859      0.844505
Sep       0.703748      0.734472
Oct       0.002263      0.072769
Nov       0.918956      0.409101
Dec       0.780640      0.065247

### <strong> Series 객체 조작 </strong>

#### Dictionary 스타일 조작

In [28]:
# Series 객체 생성
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

print(ser)    
print('a' in ser)  # [+] Key + in 키워드
print(0.25 in ser)  # [+] Value + in 키워드
print(ser.index)  # [+] 인덱스
print(ser.keys())  # [+] 키 집합
ser['0'] = 1.25  # [+] 값 추가
ser['a'] = 0.125  # [+] 값 수정
print(ser)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
True
False
Index(['a', 'b', 'c', 'd'], dtype='str')
Index(['a', 'b', 'c', 'd'], dtype='str')
a    0.125
b    0.500
c    0.750
d    1.000
0    1.250
dtype: float64

#### 배열 스타일 조작

In [30]:
print(ser['a':'c'])   # 슬라이싱
print(ser[(ser > 0.3) & (ser < 0.8)])   # 논리 연산
# 팬시 인덱싱
ind = ['a', 'e'] 
print(ser[ind])

a    0.125
b    0.500
c    0.750
dtype: float64
b    0.50
c    0.75
dtype: float64

KeyError: "['e'] not in index"

#### Pandas 객체 인덱싱
+ 정수 기반 인덱싱(암묵적, implicit)
+ 레이블 기반 인덱싱(명시적, explicit)

In [31]:
# 슬라이싱을 이용한 'a', 'b', 'c' 선택
print(ser[0:3])   # 정수 기반 인덱싱
print(ser['a':'c'])     # 레이블 기반 인덱싱

a    0.125
b    0.500
c    0.750
dtype: float64
a    0.125
b    0.500
c    0.750
dtype: float64

### <strong> DataFrame 객체 조작 </strong>

In [32]:
# 특정 Series 객체 접근
states['area']
states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [33]:
# [+] Series 객체 추가 (밀도 = 인구 / 면적)
states['density'] = states['population'] / states['area']
states

            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

#### 인덱서: ```loc```, ```iloc```

In [34]:
# Series 객체 생성
ser = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
ser

1    a
3    b
5    c
dtype: str

In [35]:
# loc 인덱서
print(ser.loc[1])
print(ser.loc[1:3])

a
1    a
3    b
dtype: str

In [37]:
# iloc 인덱서
print(ser.iloc[1])
print(ser.iloc[1:3])

b
3    b
5    c
dtype: str

In [36]:
ser.iloc[0]

'a'

In [38]:
# DataFrame 객체 = 2차원 배열
print(states.values, '\n')        # 값들을 얻어오기
print(states.T, '\n')             # 전치행렬
print(states.iloc[:3, :2], '\n')  # 정수 기반 슬라이싱
print(states.loc[: 'Illinois', : 'population'])  # 레이블 기반 슬라이싱

[[3.83325210e+07 4.23967000e+05 9.04139261e+01]
 [2.64481930e+07 6.95662000e+05 3.80187404e+01]
 [1.96511270e+07 1.41297000e+05 1.39076746e+02]
 [1.95528600e+07 1.70312000e+05 1.14806121e+02]
 [1.28821350e+07 1.49995000e+05 8.58837628e+01]]

              California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02

                Illinois
population  1.288214e+07
area        1.499950e+05
density     8.588376e+01

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [39]:
# 마스킹 + 팬시 인덱싱
states.loc[states.density > 100, ['population', 'density']]

          population     density
New York    19651127  139.076746
Florida     19552860  114.806121

In [40]:
# 값 수정
states.iloc[0, 2] = 90
states

            population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [43]:
states.loc['Texas','area'] = 169000
states

            population    area     density
California    38332521  423967   90.000000
Texas         26448193  169000   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763